### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by sh-rn** [blocknetdx/xquery-v2-testing#1]
### Goal: Basic functionality same as XQuery 1.0, improved performance & code, added state management

**To do:**
- [x] overhaul project/code structure - modular approach
- [x] add redis cache
- [x] shared between all workers
- [x] add multiprocessing
- [x] add proper state management
- [x] handle re-orgs (simple strategy: only index up to "latest - N safety blocks") - handle errors/crashes
- [x] handle start/stop ("resume" feature)
- [x] rework event log fetching, filtering (focus on improving speed) - make use of 'eth_getLogs'
- [x] keep database model and event processing from XQuery 1.0
- [x] single table database for simplicity

**QA:** - _requires more detail from the dev_
- [ ] redis cache implemented
- [ ] shared between all workers ?
- [ ] multiprocessing 
- [ ] state management ?
- [ ] handles re-orgs (simple strategy: only index up to "latest - N safety blocks") - handle errors/crashes
- [ ] handles start/stop ("resume" feature)
- [ ] rework event log fetching, filtering (focus on improving speed) - make use of 'eth_getLogs'
- [ ] database model and event processing from XQuery 1.0
- [ ] single table database for simplicity
